Fixed a failing test, added comments to yml files and fixed checkstyle errors

diff --git a/.github/workflows/flake8.yml b/.github/workflows/flake8.yml
--- a/.github/workflows/flake8.yml
+++ b/.github/workflows/flake8.yml
@@ -29,7 +29,7 @@ jobs:
     - name: Lint with pyflakes
       id: lint
       run: flake8 . > post_traces/pyflakes_trace.txt # running for all the files in the repo
-      continue-on-error: true
+      continue-on-error: true # continue the execution even if there's a checkstyle error because we want to store the analysis trace in a txt file and push it to main in the next step.
 
     - name: Commit and save the file
       run: |
@@ -44,4 +44,4 @@ jobs:
 
     - name: Fail if lint fails
       if: steps.lint.outcome == 'failure'
-      run: exit 1
+      run: exit 1 # fail the execution if "Lint with pyflakes" step comes across a check style error.
diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -29,13 +29,13 @@ jobs:
     - name: Lint with pylint
       id: lint
       run: pylint $(git ls-files '*.py') > post_traces/pylint_trace.txt # running for all the files in the repo
-      continue-on-error: true
+      continue-on-error: true  # continue the execution even if there's a checkstyle error because we want to store the analysis trace in a txt file and push it to main in the next step.
 
     - name: Commit and save the file
       run: |
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions"
-        if [ -n "$(git status --porcelain)" ]; then
+        if [ -n "$(git status --porcelain)" ];
           # Commit and push changes
           git add .
           git commit -m "Saving pylint trace"
@@ -44,4 +44,4 @@ jobs:
 
     - name: Fail if lint fails
       if: steps.lint.outcome == 'failure'
-      run: exit 1
+      run: exit 1  # fail the execution if "Lint with pylint" step comes across a check style error.
